# Este archivo es opcional, pero útil si quieres aceptar donaciones
# Puedes eliminarlo si no lo necesitas

github: # Reemplaza con tu usuario de GitHub si quieres aceptar donaciones
# custom: # Agrega URLs personalizadas si tienes otras plataformas de donación

